modLoader="javafml"
loaderVersion="[34,)"
license="LGPL-3.0"
[[mods]]
modId="janoeo_arsenal"
version="${file.jarVersion}"
displayName="Just Another Nether/Overworld/End Ores - Arsenal"
authors="AlasDiablo, lIotaMiu, Egame257 and Safyrus"
description='''
Just Another Nether/Overworld/End Ores - Arsenal by AlasDiablo, lIotaMiu, Egame257 and Safyrus
'''
[[dependencies.janoeo_arsenal]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.janoeo_arsenal]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.janoeo_arsenal]]
    modId="janoeo"
    mandatory=true
    versionRange="[4.4,)"
    ordering="AFTER"
    side="BOTH"
